name: Build DLL for RLBot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python and adjust PATH
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Especifica la versi√≥n de Python que necesitas
        architecture: 'x64'

    - name: Build DLL
      run: |
         x86_64-w64-mingw32-gcc -shared -o bot.dll -I/usr/include/python3.9 my_project/bot.c

    - name: Upload DLL
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: bot-dll
        path: bot.dll  # Reemplaza con la ruta real de tu archivo DLL de salida
